### ISSUE TITLE
Version release

### ISSUE THREAD

**Issue by rafaelha** [zxcalc/pyzx#278]
`0.8.0` was released in February. Is there a specific release schedule or would it be possible to lease a new version soon?

**Comment by jvdwetering** [comment]
There is no specific release schedule. The reason it is taking long to release something new, is because the multigraph framework is still not fully implemented. In particular, I would like to redo the graph saving to json format before a major new release, so that we can deprecate the older one that doesn't support multigraphs (and uses notation compatible with Quantomatic that nobody uses anymore).
